disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - line_length
opt_in_rules:
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift