//
//  Problem002.swift
//  ProjectEuler
//
//  Created by Søren Nielsen on 29/12/2017.
//  Copyright © 2017 Sonderby Inc. All rights reserved.
//

import Foundation

/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.
*/

struct Problem002: Problem {
    func solve() -> String {
        let fibSequence = sequence(state: (0, 1)) { state -> Int? in
            let next = state.0 + state.1
            state.0 = state.1
            state.1 = next

            if next < 4_000_000 {
                return next
            } else {
                return nil
            }
        }

        let result = fibSequence
            .filter { $0 % 2 == 0 }
            .sum()

        return "\(result)"
    }
}
